services:
  db:
    image: postgres:15
    container_name: yneo-db
    restart: always
    environment:
      POSTGRES_USER: yneo
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: yneoapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
