import { Inter, Space_Grotesk } from "next/font/google"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/lib/auth"
import ChakraProviderWrapper from "@/app/chakraProvider"

import './globals.css'

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] })
const spaceGrotesk = Space_Grotesk({ variable: "--font-space-grotesk", subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const session = await auth()

  return (
    <html lang="fr">
      <body className={`${inter.variable} ${spaceGrotesk.variable}`}>
        <div className="scanline-effect" />
        <SessionProvider session={session}>
          <ChakraProviderWrapper>
            {children}
          </ChakraProviderWrapper>
        </SessionProvider>
      </body>
    </html>
  )
}
